// <auto-generated />
using BlazorWhyUseDbContextFactory.Components.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWhyUseDbContextFactory.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231209210441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorWhyUseDbContextFactory.Components.Data.ToDoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("TaskDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Priority = 2,
                            TaskDesc = "Get gift for Mom"
                        },
                        new
                        {
                            Id = 2,
                            Priority = 1,
                            TaskDesc = "Make flight reservations for Christmas"
                        },
                        new
                        {
                            Id = 3,
                            Priority = 3,
                            TaskDesc = "Oil change for truck"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
